// Generated by tests/unit/make-spec-samples.R. Do not edit.
import type { WireSpec } from '../../../srcjs/core/spec-types';

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "globe",
    "dragRotate": true,
    "fit_bounds": false,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": true
        }
      },
      {
        "type": "scale",
        "position": "bottomleft",
        "options": {
          "maxWidth": 100,
          "unit": "metric"
        }
      },
      {
        "type": "fullscreen",
        "position": "topright"
      },
      {
        "type": "geolocate",
        "position": "topright",
        "options": {
          "trackUserLocation": false
        }
      }
    ]
  },
  ".__layers": {
    "pts": {
      "id": "pts",
      "type": "circle",
      "group": "points",
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        },
        "radius": {
          "values": {
            "ref": "radius"
          }
        },
        "lineWidth": {
          "values": {
            "ref": "lineWidth"
          }
        },
        "fillColor": {
          "encoding": "dict",
          "dict_rgba": {
            "ref": "fillColor.dict_rgba"
          },
          "codes": {
            "ref": "fillColor.codes"
          }
        },
        "lineColor": {
          "encoding": "dict",
          "dict_rgba": {
            "ref": "lineColor.dict_rgba"
          },
          "codes": {
            "ref": "lineColor.codes"
          }
        }
      },
      "base_encodings": [

      ],
      "cfg": {
        "pickable": true,
        "stroke": true,
        "radiusUnits": "meters",
        "radiusMinPixels": 2,
        "radiusMaxPixels": 40,
        "lineWidthUnits": "pixels",
        "lineWidthMinPixels": 1,
        "lineWidthMaxPixels": 4
      },
      "bbox": [
        -0.02,
        51.49,
        0.02,
        51.51
      ],
      "coordinate_origin": null,
      "dataStore": {
        "blobs": {
          "blob_92104f76cc5efca3": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtejvMP1TUIAAAAAAABOQgrXozw9Ck5C"
            },
            "length": 6
          },
          "blob_63fd1a7cd7f66f32": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AADAPwAAAEAAAGBA"
            },
            "length": 3
          },
          "blob_7f8a5dfc6e2a5990": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AQAAAAAAAAACAAAA"
            },
            "length": 3
          },
          "blob_238b1bcb4dc956a3": {
            "dtype": "u8",
            "href": {
              "data": "data:application/octet-stream;base64,+HZtzAC/xMw="
            },
            "length": 8,
            "size": 4
          },
          "blob_1ba50e2b0deb36b8": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAEAAAAAAAAA"
            },
            "length": 3
          },
          "blob_2e0c4f71fda3db0d": {
            "dtype": "u8",
            "href": {
              "data": "data:application/octet-stream;base64,AFeK/0sAVf/94zP/"
            },
            "length": 12,
            "size": 4
          }
        },
        "refs": {
          "fillColor.codes": "blob_1ba50e2b0deb36b8",
          "lineColor.codes": "blob_7f8a5dfc6e2a5990",
          "lineWidth": "blob_63fd1a7cd7f66f32",
          "lineColor.dict_rgba": "blob_2e0c4f71fda3db0d",
          "fillColor.dict_rgba": "blob_238b1bcb4dc956a3",
          "position": "blob_92104f76cc5efca3",
          "radius": "blob_63fd1a7cd7f66f32"
        }
      }
    }
  },
  ".__components": {
    "views": [

    ],
    "range": [

    ],
    "select": [

    ],
    "legends": [

    ],
    "summaries": [

    ]
  },
  ".__controls": [

  ],
  ".__panel": null
} as const satisfies WireSpec;
