// Generated by tests/unit/make-spec-samples.R. Do not edit.
import type { WireSpec } from '../../../srcjs/core/spec-types';

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "mercator",
    "dragRotate": false,
    "fit_bounds": true,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": false
        }
      }
    ]
  },
  ".__layers": {
    "circle1": {
      "id": "circle1",
      "type": "circle",
      "group": null,
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        }
      },
      "base_encodings": {
        "radius": {
          "value": 6
        },
        "lineWidth": {
          "value": 1
        },
        "fillColor": {
          "value": [
            0,
            0,
            139,
            204
          ]
        },
        "lineColor": {
          "value": [
            0,
            0,
            139,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": true,
        "radiusUnits": "pixels",
        "lineWidthUnits": "pixels"
      },
      "bbox": [
        -0.02,
        51.49,
        0.02,
        51.51
      ],
      "coordinate_origin": [
        0,
        51.5
      ],
      "tooltip": {
        "type": "template",
        "template": "{g} {v:.1f} {n} {day}",
        "html": false,
        "placeholders": [
          {
            "kind": "categorical",
            "name": "g",
            "fmt": "",
            "dict": [
              "a",
              "b"
            ],
            "codes": {
              "ref": "tpl.tooltip.1.g.codes"
            }
          },
          {
            "kind": "numeric-f32",
            "name": "v",
            "fmt": ".1f",
            "value": {
              "ref": "tpl.tooltip.2.v"
            }
          },
          {
            "kind": "numeric-u32",
            "name": "n",
            "fmt": "",
            "value": {
              "ref": "tpl.tooltip.3.n"
            }
          },
          {
            "kind": "epoch-u32",
            "name": "day",
            "fmt": "%Y-%m-%d",
            "value": {
              "ref": "tpl.tooltip.4.day"
            }
          }
        ]
      },
      "popup": {
        "type": "template",
        "template": "<b>{g}<\/b>",
        "html": true,
        "placeholders": [
          {
            "kind": "categorical",
            "name": "g",
            "fmt": "",
            "dict": [
              "a",
              "b"
            ],
            "codes": {
              "ref": "tpl.popup.1.g.codes"
            }
          }
        ]
      },
      "dataStore": {
        "blobs": {
          "blob_63fd1a7cd7f66f32": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AADAPwAAAEAAAGBA"
            },
            "length": 3
          },
          "blob_1ba50e2b0deb36b8": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAEAAAAAAAAA"
            },
            "length": 3
          },
          "blob_7911a21ec6451901": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtejvArXI7wAAAAAAAAAAArXozwK1yM8"
            },
            "length": 6
          },
          "blob_53570f46433d023a": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AQAAAAIAAAADAAAA"
            },
            "length": 3
          },
          "blob_3a93b1c04cc25125": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,ALlVaYAKV2kAXFhp"
            },
            "length": 3
          }
        },
        "refs": {
          "tpl.tooltip.3.n": "blob_53570f46433d023a",
          "tpl.tooltip.2.v": "blob_63fd1a7cd7f66f32",
          "position": "blob_7911a21ec6451901",
          "tpl.tooltip.1.g.codes": "blob_1ba50e2b0deb36b8",
          "tpl.tooltip.4.day": "blob_3a93b1c04cc25125",
          "tpl.popup.1.g.codes": "blob_1ba50e2b0deb36b8"
        }
      }
    }
  },
  ".__components": {
    "views": [

    ],
    "range": [

    ],
    "select": [

    ],
    "legends": [

    ],
    "summaries": [

    ]
  },
  ".__controls": [

  ],
  ".__panel": null
} as const satisfies WireSpec;
