// Generated by tests/unit/make-spec-samples.R. Do not edit.
import type { WireSpec } from '../../../srcjs/core/spec-types';

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "mercator",
    "dragRotate": false,
    "fit_bounds": true,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": false
        }
      }
    ]
  },
  ".__layers": [

  ],
  ".__components": {
    "views": [

    ],
    "range": [

    ],
    "select": [

    ],
    "legends": [

    ],
    "summaries": [

    ]
  },
  ".__controls": [

  ],
  ".__panel": null
} as const satisfies WireSpec;
