// Generated by tests/unit/make-spec-samples.R. Do not edit.
import type { WireSpec } from '../../../srcjs/core/spec-types';

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "mercator",
    "dragRotate": false,
    "fit_bounds": true,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": false
        }
      }
    ]
  },
  ".__layers": {
    "a": {
      "id": "a",
      "type": "circle",
      "group": null,
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        }
      },
      "base_encodings": {
        "radius": {
          "value": 6
        },
        "lineWidth": {
          "value": 1
        },
        "fillColor": {
          "value": [
            30,
            144,
            255,
            204
          ]
        },
        "lineColor": {
          "value": [
            0,
            0,
            139,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": true,
        "radiusUnits": "pixels",
        "lineWidthUnits": "pixels"
      },
      "bbox": [
        -0.02,
        51.49,
        0.02,
        51.51
      ],
      "coordinate_origin": [
        0,
        51.5
      ],
      "dataStore": {
        "blobs": {
          "blob_63fd1a7cd7f66f32": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AADAPwAAAEAAAGBA"
            },
            "length": 3
          },
          "blob_1ba50e2b0deb36b8": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAEAAAAAAAAA"
            },
            "length": 3
          },
          "blob_7911a21ec6451901": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtejvArXI7wAAAAAAAAAAArXozwK1yM8"
            },
            "length": 6
          }
        },
        "refs": {
          "position": "blob_7911a21ec6451901",
          "flt.rng_1.values": "blob_63fd1a7cd7f66f32",
          "flt.sel_1.codes": "blob_1ba50e2b0deb36b8"
        }
      }
    },
    "b": {
      "id": "b",
      "type": "circle",
      "group": null,
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        }
      },
      "base_encodings": {
        "radius": {
          "value": 6
        },
        "lineWidth": {
          "value": 1
        },
        "fillColor": {
          "value": [
            30,
            144,
            255,
            204
          ]
        },
        "lineColor": {
          "value": [
            0,
            0,
            139,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": true,
        "radiusUnits": "pixels",
        "lineWidthUnits": "pixels"
      },
      "bbox": [
        0.04,
        51.5,
        0.06,
        51.5
      ],
      "coordinate_origin": [
        0.05000000000001137,
        51.5
      ],
      "dataStore": {
        "blobs": {
          "blob_22a4bd420abc54f3": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtcjvAAAAAAAAAAAAAAAAArXIzwAAAAA"
            },
            "length": 6
          },
          "blob_2658ae0489a3c5cf": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AQAAAAAAAAABAAAA"
            },
            "length": 3
          },
          "blob_1c9a9b588c81b1d9": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAAAwH8AAIBA"
            },
            "length": 3
          }
        },
        "refs": {
          "flt.sel_2.codes": "blob_2658ae0489a3c5cf",
          "flt.rng_2.values": "blob_1c9a9b588c81b1d9",
          "position": "blob_22a4bd420abc54f3"
        }
      }
    }
  },
  ".__components": {
    "views": [

    ],
    "range": {
      "rng_1": {
        "type": "range",
        "id": "rng_1",
        "layer": "a",
        "bind": "filters",
        "position": null,
        "label": "v",
        "default": null,
        "min": 1.5,
        "max": 3.5,
        "step": null,
        "live": true,
        "values": {
          "ref": "flt.rng_1.values"
        },
        "values_ref_hint": "flt.rng_1.values"
      },
      "rng_2": {
        "type": "range",
        "id": "rng_2",
        "layer": "b",
        "bind": "filters",
        "position": null,
        "label": "v",
        "default": null,
        "min": 0,
        "max": 4,
        "step": null,
        "live": true,
        "values": {
          "ref": "flt.rng_2.values"
        },
        "values_ref_hint": "flt.rng_2.values"
      }
    },
    "select": {
      "sel_1": {
        "type": "select",
        "id": "sel_1",
        "layer": "a",
        "bind": "filters",
        "position": null,
        "label": "g",
        "multi": true,
        "dropdown": null,
        "searchable": true,
        "dict": [
          "a",
          "b"
        ],
        "default": null,
        "max_levels": null,
        "freq": [
          2,
          1
        ],
        "top_indices": [
          0,
          1
        ],
        "codes": {
          "ref": "flt.sel_1.codes"
        },
        "codes_ref_hint": "flt.sel_1.codes"
      },
      "sel_2": {
        "type": "select",
        "id": "sel_2",
        "layer": "b",
        "bind": "filters",
        "position": null,
        "label": "g",
        "multi": true,
        "dropdown": null,
        "searchable": true,
        "dict": [
          "(Missing)",
          "c"
        ],
        "default": null,
        "max_levels": null,
        "freq": [
          1,
          2
        ],
        "top_indices": [
          1,
          0
        ],
        "codes": {
          "ref": "flt.sel_2.codes"
        },
        "codes_ref_hint": "flt.sel_2.codes"
      }
    },
    "legends": [

    ],
    "summaries": [

    ]
  },
  ".__controls": {
    "filters": {
      "type": "filters",
      "controls": {
        "g": {
          "type": "select",
          "label": "g",
          "members": [
            "sel_1",
            "sel_2"
          ],
          "dict": [
            "a",
            "b",
            "(Missing)",
            "c"
          ],
          "multi": true,
          "searchable": true,
          "freq": [
            2,
            1,
            1,
            2
          ],
          "top_indices": [
            0,
            3,
            1,
            2
          ]
        },
        "v": {
          "type": "range",
          "label": "v",
          "members": [
            "rng_1",
            "rng_2"
          ],
          "domain": {
            "min": 0,
            "max": 4
          },
          "live": true
        }
      },
      "order": [
        "g",
        "v"
      ]
    }
  },
  ".__panel": null
} as const satisfies WireSpec;
