// Generated by tests/unit/make-spec-samples.R. Do not edit.
import type { WireSpec } from '../../../srcjs/core/spec-types';

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "mercator",
    "dragRotate": false,
    "fit_bounds": true,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": false
        }
      }
    ]
  },
  ".__layers": {
    "icon1": {
      "id": "icon1",
      "type": "icon",
      "group": null,
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        },
        "fillColor": {
          "encoding": "dict",
          "dict_rgba": {
            "ref": "fillColor.dict_rgba"
          },
          "codes": {
            "ref": "fillColor.codes"
          }
        }
      },
      "base_encodings": {
        "size": {
          "value": 24
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": false,
        "sizeUnits": "meters",
        "sizeMinPixels": 4,
        "sizeMaxPixels": 64,
        "icon": "star",
        "mask": true,
        "occlude": false
      },
      "bbox": [
        -0.02,
        51.49,
        0.02,
        51.51
      ],
      "coordinate_origin": [
        0,
        51.5
      ],
      "dataStore": {
        "blobs": {
          "blob_63fd1a7cd7f66f32": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AADAPwAAAEAAAGBA"
            },
            "length": 3
          },
          "blob_1ba50e2b0deb36b8": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAEAAAAAAAAA"
            },
            "length": 3
          },
          "blob_af5f4e40277b3c6f": {
            "dtype": "u8",
            "href": {
              "data": "data:application/octet-stream;base64,+HZt/wC/xP8="
            },
            "length": 8,
            "size": 4
          },
          "blob_7911a21ec6451901": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtejvArXI7wAAAAAAAAAAArXozwK1yM8"
            },
            "length": 6
          }
        },
        "refs": {
          "fillColor.codes": "blob_1ba50e2b0deb36b8",
          "fillColor.dict_rgba": "blob_af5f4e40277b3c6f",
          "vw.views1.by value.size": "blob_63fd1a7cd7f66f32",
          "position": "blob_7911a21ec6451901"
        }
      }
    },
    "marker1": {
      "id": "marker1",
      "type": "marker",
      "group": null,
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        },
        "size": {
          "values": {
            "ref": "size"
          }
        }
      },
      "base_encodings": {
        "fillColor": {
          "value": [
            255,
            0,
            0,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": false,
        "icon": "geo_alt_fill",
        "iconStroke": "geo_alt",
        "sizeUnits": "pixels",
        "sizeMaxPixels": 48,
        "mask": true,
        "occlude": false
      },
      "bbox": [
        -0.02,
        51.49,
        0.02,
        51.51
      ],
      "coordinate_origin": [
        0,
        51.5
      ],
      "dataStore": {
        "blobs": {
          "blob_63fd1a7cd7f66f32": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AADAPwAAAEAAAGBA"
            },
            "length": 3
          },
          "blob_7911a21ec6451901": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtejvArXI7wAAAAAAAAAAArXozwK1yM8"
            },
            "length": 6
          }
        },
        "refs": {
          "size": "blob_63fd1a7cd7f66f32",
          "position": "blob_7911a21ec6451901"
        }
      }
    }
  },
  ".__components": {
    "views": {
      "views1": {
        "type": "views",
        "id": "views1",
        "layer": "icon1",
        "bind": "views1",
        "position": null,
        "motion": {
          "duration": 750,
          "easing": "smoothstep"
        },
        "views": {
          "big": {
            "encodings": {
              "size": {
                "value": 40
              }
            }
          },
          "by value": {
            "encodings": {
              "size": {
                "value": {
                  "ref": "vw.views1.by value.size"
                }
              }
            }
          }
        }
      }
    },
    "range": [

    ],
    "select": [

    ],
    "legends": [

    ],
    "summaries": [

    ]
  },
  ".__controls": {
    "views1": {
      "type": "views",
      "members": [
        "views1"
      ],
      "view_names": [
        "big",
        "by value"
      ],
      "default": "big"
    }
  },
  ".__panel": null
} as const satisfies WireSpec;
