// Generated by tests/unit/make-spec-samples.R. Do not edit.
import type { WireSpec } from '../../../srcjs/core/spec-types';

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "mercator",
    "dragRotate": false,
    "fit_bounds": true,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": false
        }
      }
    ]
  },
  ".__layers": {
    "circle1": {
      "id": "circle1",
      "type": "circle",
      "group": null,
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        }
      },
      "base_encodings": {
        "radius": {
          "value": 6
        },
        "lineWidth": {
          "value": 1
        },
        "fillColor": {
          "value": [
            30,
            144,
            255,
            204
          ]
        },
        "lineColor": {
          "value": [
            0,
            0,
            139,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": true,
        "radiusUnits": "pixels",
        "lineWidthUnits": "pixels"
      },
      "bbox": [
        -0.02,
        51.49,
        0.02,
        51.51
      ],
      "coordinate_origin": [
        0,
        51.5
      ],
      "dataStore": {
        "blobs": {
          "blob_7911a21ec6451901": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtejvArXI7wAAAAAAAAAAArXozwK1yM8"
            },
            "length": 6
          }
        },
        "refs": {
          "position": "blob_7911a21ec6451901"
        }
      }
    }
  },
  ".__components": {
    "views": {
      "views1": {
        "type": "views",
        "id": "views1",
        "layer": "circle1",
        "bind": "views1",
        "position": null,
        "motion": {
          "duration": 750,
          "easing": "smoothstep"
        },
        "views": {
          "a": {
            "encodings": {
              "radius": {
                "value": 4
              }
            }
          },
          "b": {
            "encodings": {
              "radius": {
                "value": 8
              }
            }
          }
        }
      }
    },
    "range": [

    ],
    "select": [

    ],
    "legends": {
      "legend1": {
        "type": "legends",
        "id": "legend1",
        "bind": "legend1",
        "position": "bottomleft",
        "legend": {
          "title": "Groups",
          "type": "categorical",
          "items": [
            {
              "label": "a",
              "color": "red",
              "shape": "circle",
              "size": 10
            },
            {
              "label": "b",
              "color": "blue",
              "shape": "icon",
              "icon": "geo_alt_fill",
              "size": 14
            }
          ]
        },
        "when": null
      },
      "legend2": {
        "type": "legends",
        "id": "legend2",
        "bind": "scale",
        "position": "topleft",
        "legend": {
          "title": null,
          "type": "continuous",
          "scale": {
            "range": [
              0,
              1
            ],
            "labels": [
              "low",
              "high"
            ],
            "breaks": [
              0,
              1
            ],
            "gradient": [
              "white",
              "red"
            ]
          },
          "shape": "line",
          "size": 4
        },
        "when": {
          "layer": "circle1",
          "view": [
            "a",
            "b"
          ]
        }
      }
    },
    "summaries": [

    ]
  },
  ".__controls": {
    "views1": {
      "type": "views",
      "members": [
        "views1"
      ],
      "view_names": [
        "a",
        "b"
      ],
      "default": "a"
    },
    "legend1": {
      "type": "legends",
      "members": [
        "legend1"
      ],
      "position": "bottomleft"
    },
    "scale": {
      "type": "legends",
      "members": [
        "legend2"
      ],
      "position": "topleft"
    }
  },
  ".__panel": null
} as const satisfies WireSpec;
