// Generated by tests/unit/make-spec-samples.R. Do not edit.
import type { WireSpec } from '../../../srcjs/core/spec-types';

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "mercator",
    "dragRotate": false,
    "fit_bounds": true,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": false
        }
      }
    ]
  },
  ".__layers": {
    "circle1": {
      "id": "circle1",
      "type": "circle",
      "group": null,
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        }
      },
      "base_encodings": {
        "radius": {
          "value": 6
        },
        "lineWidth": {
          "value": 1
        },
        "fillColor": {
          "value": [
            30,
            144,
            255,
            204
          ]
        },
        "lineColor": {
          "value": [
            0,
            0,
            139,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": true,
        "radiusUnits": "pixels",
        "lineWidthUnits": "pixels"
      },
      "bbox": [
        -0.02,
        51.49,
        -0.02,
        51.49
      ],
      "coordinate_origin": [
        -0.02000000000001023,
        51.49
      ],
      "tooltip": {
        "type": "template",
        "template": "{g}",
        "html": false,
        "placeholders": [
          {
            "kind": "categorical",
            "name": "g",
            "fmt": "",
            "dict": "a",
            "codes": {
              "ref": "tpl.tooltip.1.g.codes"
            }
          }
        ]
      },
      "dataStore": {
        "blobs": {
          "blob_df695e0ff10406e5": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAAAAAA="
            },
            "length": 2
          },
          "blob_1d5e392288266722": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAA=="
            },
            "length": 1
          }
        },
        "refs": {
          "position": "blob_df695e0ff10406e5",
          "tpl.tooltip.1.g.codes": "blob_1d5e392288266722",
          "flt.sel_1.codes": "blob_1d5e392288266722"
        }
      }
    }
  },
  ".__components": {
    "views": [

    ],
    "range": [

    ],
    "select": {
      "sel_1": {
        "type": "select",
        "id": "sel_1",
        "layer": "circle1",
        "bind": "filters_1",
        "position": null,
        "label": "g",
        "multi": true,
        "dropdown": null,
        "searchable": true,
        "dict": [
          "a"
        ],
        "default": "a",
        "max_levels": null,
        "freq": [
          1
        ],
        "top_indices": [
          0
        ],
        "codes": {
          "ref": "flt.sel_1.codes"
        },
        "codes_ref_hint": "flt.sel_1.codes"
      }
    },
    "legends": {
      "legend1": {
        "type": "legends",
        "id": "legend1",
        "bind": "legend1",
        "position": "bottomleft",
        "legend": {
          "title": null,
          "type": "categorical",
          "items": [
            {
              "label": "only",
              "color": "red",
              "shape": "square"
            }
          ]
        },
        "when": null
      },
      "legend2": {
        "type": "legends",
        "id": "legend2",
        "bind": "legend2",
        "position": "bottomleft",
        "legend": {
          "title": null,
          "type": "continuous",
          "scale": {
            "range": [
              0,
              1
            ],
            "labels": "low",
            "breaks": 0.5,
            "gradient": [
              "white",
              "red"
            ]
          },
          "shape": "square",
          "size": 12
        },
        "when": {
          "layer": null,
          "view": [
            "a"
          ]
        }
      }
    },
    "summaries": [

    ]
  },
  ".__controls": {
    "filters_1": {
      "type": "filters",
      "controls": {
        "g": {
          "type": "select",
          "label": "g",
          "members": [
            "sel_1"
          ],
          "dict": [
            "a"
          ],
          "default": "a",
          "multi": true,
          "searchable": true,
          "freq": [
            1
          ],
          "top_indices": [
            0
          ]
        }
      },
      "order": [
        "g"
      ]
    },
    "legend1": {
      "type": "legends",
      "members": [
        "legend1"
      ],
      "position": "bottomleft"
    },
    "legend2": {
      "type": "legends",
      "members": [
        "legend2"
      ],
      "position": "bottomleft"
    }
  },
  ".__panel": null
} as const satisfies WireSpec;
