// Generated by tests/unit/make-spec-samples.R. Do not edit.
import type { WireSpec } from '../../../srcjs/core/spec-types';

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "mercator",
    "dragRotate": false,
    "fit_bounds": true,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": false
        }
      }
    ]
  },
  ".__layers": {
    "line1": {
      "id": "line1",
      "type": "line",
      "group": null,
      "data_columns": {
        "path": {
          "positions": {
            "ref": "path.pos"
          },
          "path_starts": {
            "ref": "path.starts"
          },
          "length": 2,
          "size": 2
        },
        "feature_index": {
          "values": {
            "ref": "feature_index"
          }
        }
      },
      "base_encodings": {
        "lineWidth": {
          "value": 4
        },
        "lineColor": {
          "value": [
            51,
            136,
            255,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": false,
        "widthUnits": "pixels",
        "widthMinPixels": 1,
        "widthMaxPixels": 20
      },
      "bbox": [
        -0.03,
        51.49,
        0.03,
        51.51
      ],
      "coordinate_origin": [
        0,
        51.5
      ],
      "tooltip": {
        "type": "template",
        "template": "plain",
        "html": false,
        "placeholders": [

        ]
      },
      "dataStore": {
        "blobs": {
          "blob_3c203591ca709011": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAIAAAA="
            },
            "length": 2
          },
          "blob_af5f4e40277b3c6f": {
            "dtype": "u8",
            "href": {
              "data": "data:application/octet-stream;base64,+HZt/wC/xP8="
            },
            "length": 8,
            "size": 4
          },
          "blob_8cc31fa0072eaf1b": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,j8L1vArXI7yPwvU8CtcjvI/C9bwK1yM8j8L1PArXIzw="
            },
            "length": 8
          },
          "blob_8a2d79fb95a2b08c": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AACAPwAAAEA="
            },
            "length": 2
          },
          "blob_576eb50f3b1cc0f5": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAEAAAA="
            },
            "length": 2
          },
          "blob_f49205f5407e5da6": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAEAAAA="
            },
            "length": 2
          }
        },
        "refs": {
          "vw.views1.by value.lineWidth": "blob_8a2d79fb95a2b08c",
          "vw.views1.by value.lineColor.dict": "blob_af5f4e40277b3c6f",
          "vw.views1.by value.lineColor.codes": "blob_576eb50f3b1cc0f5",
          "path.starts": "blob_3c203591ca709011",
          "feature_index": "blob_f49205f5407e5da6",
          "path.pos": "blob_8cc31fa0072eaf1b"
        }
      }
    }
  },
  ".__components": {
    "views": {
      "views1": {
        "type": "views",
        "id": "views1",
        "layer": "line1",
        "bind": "views1",
        "position": "topright",
        "motion": {
          "duration": 500,
          "easing": "linear"
        },
        "views": {
          "thin": {
            "encodings": {
              "lineWidth": {
                "value": 2
              }
            }
          },
          "by value": {
            "encodings": {
              "lineWidth": {
                "value": {
                  "ref": "vw.views1.by value.lineWidth"
                }
              },
              "lineColor": {
                "encoding": "dict",
                "dict_rgba": {
                  "ref": "vw.views1.by value.lineColor.dict"
                },
                "codes": {
                  "ref": "vw.views1.by value.lineColor.codes"
                },
                "dict_rgba_ref_hint": "vw.views1.by value.lineColor.dict",
                "codes_ref_hint": "vw.views1.by value.lineColor.codes"
              }
            }
          },
          "flat": {
            "encodings": {
              "lineColor": {
                "value": [
                  255,
                  0,
                  0,
                  255
                ]
              }
            }
          }
        }
      }
    },
    "range": [

    ],
    "select": [

    ],
    "legends": [

    ],
    "summaries": [

    ]
  },
  ".__controls": {
    "views1": {
      "type": "views",
      "members": [
        "views1"
      ],
      "position": "topright",
      "view_names": [
        "thin",
        "by value",
        "flat"
      ],
      "default": "thin"
    }
  },
  ".__panel": null
} as const satisfies WireSpec;
