// Generated by tests/unit/make-spec-samples.R. Do not edit.
import type { WireSpec } from '../../../srcjs/core/spec-types';

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "mercator",
    "dragRotate": false,
    "fit_bounds": true,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": false
        }
      }
    ]
  },
  ".__layers": {
    "polygon1": {
      "id": "polygon1",
      "type": "polygon",
      "group": null,
      "data_columns": {
        "polygon": {
          "positions": {
            "ref": "poly.pos"
          },
          "ring_starts": {
            "ref": "poly.rings"
          },
          "poly_starts": {
            "ref": "poly.starts"
          },
          "length": 3,
          "size": 2
        },
        "feature_index": {
          "values": {
            "ref": "feature_index"
          }
        },
        "fillColor": {
          "encoding": "dict",
          "dict_rgba": {
            "ref": "fillColor.dict_rgba"
          },
          "codes": {
            "ref": "fillColor.codes"
          }
        }
      },
      "base_encodings": {
        "lineWidth": {
          "value": 2
        },
        "lineColor": {
          "value": [
            0,
            0,
            139,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": true,
        "lineWidthUnits": "pixels",
        "elevationScale": 1
      },
      "bbox": [
        -0.04,
        51.49,
        0.04,
        51.51
      ],
      "coordinate_origin": [
        0,
        51.5
      ],
      "dataStore": {
        "blobs": {
          "blob_f92a68509752f224": {
            "dtype": "u8",
            "href": {
              "data": "data:application/octet-stream;base64,AAD/mf8AAJk="
            },
            "length": 8,
            "size": 4
          },
          "blob_20f6c88fcef94d11": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AQAAAAEAAAAAAAAA"
            },
            "length": 3
          },
          "blob_bb94f671c74bd586": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAEAAAACAAAA"
            },
            "length": 3
          },
          "blob_41b2ab61d2507f98": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAgQQAAIEEAAIA/"
            },
            "length": 3
          },
          "blob_00134116cff37b3d": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAgQQAAgD8="
            },
            "length": 2
          },
          "blob_f387b7a08439dd38": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAAAAAABAAAA"
            },
            "length": 3
          },
          "blob_3513cf0448183cea": {
            "dtype": "u8",
            "href": {
              "data": "data:application/octet-stream;base64,SwBVmf3jM5k="
            },
            "length": 8,
            "size": 4
          },
          "blob_6a44fd70183b1de8": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAQAAAAIAAAA"
            },
            "length": 3
          },
          "blob_86f7d73c8ea02dcd": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtcjvQrXI7wK16O8CtcjvArXo7wK1yM8CtcjvQrXIzwK1yO8CtcjvArXIzwK1yO8CtcjPArXIzwK1yO8CtcjPArXozwK1yO8CtcjPQrXI7wK1yM9CtcjPArXozwK1yM8"
            },
            "length": 24
          },
          "blob_a7f6aa3ad3b93683": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAAAAAABAAAA"
            },
            "length": 3
          }
        },
        "refs": {
          "fillColor.codes": "blob_20f6c88fcef94d11",
          "sm.sum_5.values": "blob_00134116cff37b3d",
          "poly.rings": "blob_6a44fd70183b1de8",
          "poly.pos": "blob_86f7d73c8ea02dcd",
          "sm.sum_3.values": "blob_00134116cff37b3d",
          "vw.views1.scale.fillColor.codes": "blob_20f6c88fcef94d11",
          "fillColor.dict_rgba": "blob_f92a68509752f224",
          "poly.starts": "blob_bb94f671c74bd586",
          "flt.rng_1.values": "blob_41b2ab61d2507f98",
          "feature_index": "blob_f387b7a08439dd38",
          "flt.sel_1.codes": "blob_a7f6aa3ad3b93683",
          "sm.sum_2.values": "blob_00134116cff37b3d",
          "vw.views1.scale.fillColor.dict": "blob_3513cf0448183cea",
          "sm.sum_4.values": "blob_00134116cff37b3d"
        }
      }
    }
  },
  ".__components": {
    "views": {
      "views1": {
        "type": "views",
        "id": "views1",
        "layer": "polygon1",
        "bind": "views",
        "position": null,
        "motion": {
          "duration": 750,
          "easing": "smoothstep"
        },
        "views": {
          "scale": {
            "encodings": {
              "fillColor": {
                "encoding": "dict",
                "dict_rgba": {
                  "ref": "vw.views1.scale.fillColor.dict"
                },
                "codes": {
                  "ref": "vw.views1.scale.fillColor.codes"
                },
                "dict_rgba_ref_hint": "vw.views1.scale.fillColor.dict",
                "codes_ref_hint": "vw.views1.scale.fillColor.codes"
              }
            }
          },
          "flat": {
            "encodings": {
              "fillColor": {
                "value": [
                  255,
                  0,
                  0,
                  153
                ]
              }
            }
          }
        }
      }
    },
    "range": {
      "rng_1": {
        "type": "range",
        "id": "rng_1",
        "layer": "polygon1",
        "bind": "filters",
        "position": null,
        "label": "v",
        "default": [
          1,
          5
        ],
        "min": 1,
        "max": 10,
        "step": 0.5,
        "live": false,
        "values": {
          "ref": "flt.rng_1.values"
        },
        "values_ref_hint": "flt.rng_1.values"
      }
    },
    "select": {
      "sel_1": {
        "type": "select",
        "id": "sel_1",
        "layer": "polygon1",
        "bind": "filters",
        "position": null,
        "label": "g",
        "multi": true,
        "dropdown": true,
        "searchable": true,
        "dict": [
          "a",
          "b"
        ],
        "default": [
          "a",
          "b"
        ],
        "max_levels": 5,
        "freq": [
          1,
          1
        ],
        "top_indices": [
          0,
          1
        ],
        "codes": {
          "ref": "flt.sel_1.codes"
        },
        "codes_ref_hint": "flt.sel_1.codes"
      }
    },
    "legends": [

    ],
    "summaries": {
      "sum_1": {
        "type": "summaries",
        "id": "sum_1",
        "layer": "polygon1",
        "bind": "summaries",
        "position": null,
        "label": "n",
        "op": "count"
      },
      "sum_2": {
        "type": "summaries",
        "id": "sum_2",
        "layer": "polygon1",
        "bind": "summaries",
        "position": null,
        "label": "sum",
        "op": "sum",
        "digits": 1,
        "prefix": "$",
        "suffix": " m",
        "na_rm": true,
        "values": {
          "ref": "sm.sum_2.values"
        },
        "values_ref_hint": "sm.sum_2.values"
      },
      "sum_3": {
        "type": "summaries",
        "id": "sum_3",
        "layer": "polygon1",
        "bind": "summaries",
        "position": null,
        "label": "mean",
        "op": "mean",
        "na_rm": true,
        "values": {
          "ref": "sm.sum_3.values"
        },
        "values_ref_hint": "sm.sum_3.values"
      },
      "sum_4": {
        "type": "summaries",
        "id": "sum_4",
        "layer": "polygon1",
        "bind": "summaries",
        "position": null,
        "label": "min",
        "op": "min",
        "na_rm": true,
        "values": {
          "ref": "sm.sum_4.values"
        },
        "values_ref_hint": "sm.sum_4.values"
      },
      "sum_5": {
        "type": "summaries",
        "id": "sum_5",
        "layer": "polygon1",
        "bind": "summaries",
        "position": null,
        "label": "max",
        "op": "max",
        "na_rm": true,
        "values": {
          "ref": "sm.sum_5.values"
        },
        "values_ref_hint": "sm.sum_5.values"
      }
    }
  },
  ".__controls": {
    "views": {
      "type": "views",
      "members": [
        "views1"
      ],
      "view_names": [
        "scale",
        "flat"
      ],
      "default": "scale"
    },
    "filters": {
      "type": "filters",
      "controls": {
        "g": {
          "type": "select",
          "label": "g",
          "members": [
            "sel_1"
          ],
          "dict": [
            "a",
            "b"
          ],
          "default": [
            "a",
            "b"
          ],
          "multi": true,
          "dropdown": true,
          "searchable": true,
          "max_levels": 5,
          "freq": [
            1,
            1
          ],
          "top_indices": [
            0,
            1
          ]
        },
        "v": {
          "type": "range",
          "label": "v",
          "members": [
            "rng_1"
          ],
          "domain": {
            "min": 1,
            "max": 10
          },
          "default": [
            1,
            5
          ],
          "step": 0.5,
          "live": false
        }
      },
      "order": [
        "g",
        "v"
      ]
    },
    "summaries": {
      "type": "summaries",
      "rows": {
        "n": {
          "op": "count",
          "label": "n",
          "members": [
            "sum_1"
          ]
        },
        "sum": {
          "op": "sum",
          "label": "sum",
          "members": [
            "sum_2"
          ],
          "digits": 1,
          "prefix": "$",
          "suffix": " m",
          "na_rm": true
        },
        "mean": {
          "op": "mean",
          "label": "mean",
          "members": [
            "sum_3"
          ],
          "na_rm": true
        },
        "min": {
          "op": "min",
          "label": "min",
          "members": [
            "sum_4"
          ],
          "na_rm": true
        },
        "max": {
          "op": "max",
          "label": "max",
          "members": [
            "sum_5"
          ],
          "na_rm": true
        }
      },
      "order": [
        "n",
        "sum",
        "mean",
        "min",
        "max"
      ]
    }
  },
  ".__panel": {
    "title": "Panel",
    "description": "About",
    "icon": null,
    "dividers": true,
    "position": "bottomright",
    "sections": [
      {
        "id": "views"
      },
      {
        "id": "filters"
      },
      {
        "id": "summaries"
      }
    ]
  }
} as const satisfies WireSpec;
