// Generated by tests/unit/make-spec-samples.R. Do not edit.
import type { WireSpec } from '../../../srcjs/core/spec-types';

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "mercator",
    "dragRotate": false,
    "fit_bounds": true,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": false
        }
      }
    ]
  },
  ".__layers": {
    "circle1": {
      "id": "circle1",
      "type": "circle",
      "group": null,
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        }
      },
      "base_encodings": {
        "radius": {
          "value": 6
        },
        "lineWidth": {
          "value": 1
        },
        "fillColor": {
          "value": [
            30,
            144,
            255,
            204
          ]
        },
        "lineColor": {
          "value": [
            0,
            0,
            139,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": true,
        "radiusUnits": "pixels",
        "lineWidthUnits": "pixels"
      },
      "bbox": [
        -0.04,
        51.5,
        0.04,
        51.5
      ],
      "coordinate_origin": [
        0,
        51.5
      ],
      "dataStore": {
        "blobs": {
          "blob_be1fb94914a77f7b": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,mpmZPgAAAD8zMzM/ZmZmP83MjD8="
            },
            "length": 5
          },
          "blob_74e759a52731a57a": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtcjvQAAAAAK16O8AAAAAAAAAAAAAAAACtejPAAAAAAK1yM9AAAAAA=="
            },
            "length": 10
          }
        },
        "refs": {
          "position": "blob_74e759a52731a57a",
          "flt.rng_1.values": "blob_be1fb94914a77f7b"
        }
      }
    }
  },
  ".__components": {
    "views": [

    ],
    "range": {
      "rng_1": {
        "type": "range",
        "id": "rng_1",
        "layer": "circle1",
        "bind": "filters",
        "position": null,
        "label": "v",
        "default": null,
        "min": 0.3,
        "max": 1.1,
        "step": null,
        "live": true,
        "values": {
          "ref": "flt.rng_1.values"
        },
        "values_ref_hint": "flt.rng_1.values"
      }
    },
    "select": [

    ],
    "legends": [

    ],
    "summaries": {
      "sum_1": {
        "type": "summaries",
        "id": "sum_1",
        "layer": "circle1",
        "bind": "summaries",
        "position": null,
        "label": "n",
        "op": "count"
      }
    }
  },
  ".__controls": {
    "filters": {
      "type": "filters",
      "controls": {
        "v": {
          "type": "range",
          "label": "v",
          "members": [
            "rng_1"
          ],
          "domain": {
            "min": 0.3,
            "max": 1.1
          },
          "live": true
        }
      },
      "order": [
        "v"
      ]
    },
    "summaries": {
      "type": "summaries",
      "rows": {
        "n": {
          "op": "count",
          "label": "n",
          "members": [
            "sum_1"
          ]
        }
      },
      "order": [
        "n"
      ]
    }
  },
  ".__panel": null
} as const satisfies WireSpec;
