// Generated by tests/unit/make-spec-samples.R. Do not edit.
// Not checked against WireSpec.

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "mercator",
    "dragRotate": false,
    "fit_bounds": true,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": false
        }
      }
    ]
  },
  ".__layers": {
    "circle1": {
      "id": "circle1",
      "type": "circle",
      "group": null,
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        }
      },
      "base_encodings": {
        "radius": {
          "value": 6
        },
        "lineWidth": {
          "value": 1
        },
        "fillColor": {
          "value": [
            30,
            144,
            255,
            204
          ]
        },
        "lineColor": {
          "value": [
            0,
            0,
            139,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": true,
        "radiusUnits": "pixels",
        "lineWidthUnits": "pixels"
      },
      "bbox": [
        -0.02,
        51.49,
        0.02,
        51.51
      ],
      "coordinate_origin": [
        0,
        51.5
      ],
      "dataStore": {
        "blobs": {
          "blob_714cde9ab75bb4c3": {
            "dtype": "u32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAAAEAAAACAAAA"
            },
            "length": 3
          },
          "blob_7911a21ec6451901": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtejvArXI7wAAAAAAAAAAArXozwK1yM8"
            },
            "length": 6
          }
        },
        "refs": {
          "position": "blob_7911a21ec6451901",
          "flt.sel_1.codes": "blob_714cde9ab75bb4c3"
        }
      }
    }
  },
  ".__components": {
    "views": [

    ],
    "range": [

    ],
    "select": {
      "sel_1": {
        "type": "select",
        "id": "sel_1",
        "layer": "circle1",
        "bind": "filters_1",
        "position": null,
        "label": "n",
        "multi": true,
        "dropdown": null,
        "searchable": true,
        "dict": [
          "1",
          "2",
          "3"
        ],
        "default": 2,
        "max_levels": null,
        "freq": [
          1,
          1,
          1
        ],
        "top_indices": [
          0,
          1,
          2
        ],
        "codes": {
          "ref": "flt.sel_1.codes"
        },
        "codes_ref_hint": "flt.sel_1.codes"
      }
    },
    "legends": [

    ],
    "summaries": [

    ]
  },
  ".__controls": {
    "filters_1": {
      "type": "filters",
      "controls": {
        "n": {
          "type": "select",
          "label": "n",
          "members": [
            "sel_1"
          ],
          "dict": [
            "1",
            "2",
            "3"
          ],
          "default": 2,
          "multi": true,
          "searchable": true,
          "freq": [
            1,
            1,
            1
          ],
          "top_indices": [
            0,
            1,
            2
          ]
        }
      },
      "order": [
        "n"
      ]
    }
  },
  ".__panel": null
} as const;
