// Generated by tests/unit/make-spec-samples.R. Do not edit.
import type { WireSpec } from '../../../srcjs/core/spec-types';

export default {
  "map_options": {
    "style": "https://basemaps.cartocdn.com/gl/positron-gl-style/style.json",
    "projection": "mercator",
    "dragRotate": false,
    "fit_bounds": true,
    "controls": [
      {
        "type": "navigation",
        "position": "topright",
        "options": {
          "showZoom": true,
          "showCompass": false
        }
      }
    ]
  },
  ".__layers": {
    "a": {
      "id": "a",
      "type": "circle",
      "group": null,
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        }
      },
      "base_encodings": {
        "radius": {
          "value": 6
        },
        "lineWidth": {
          "value": 1
        },
        "fillColor": {
          "value": [
            30,
            144,
            255,
            204
          ]
        },
        "lineColor": {
          "value": [
            0,
            0,
            139,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": true,
        "radiusUnits": "pixels",
        "lineWidthUnits": "pixels"
      },
      "bbox": [
        -0.02,
        51.5,
        0.02,
        51.5
      ],
      "coordinate_origin": [
        0,
        51.5
      ],
      "dataStore": {
        "blobs": {
          "blob_e3184e13cd1bc1f1": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AACAvwAAwH8AAIA/"
            },
            "length": 3
          },
          "blob_b506867099007436": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtejvAAAAAAAAAAAAAAAAArXozwAAAAA"
            },
            "length": 6
          }
        },
        "refs": {
          "sm.sum_5.values": "blob_e3184e13cd1bc1f1",
          "sm.sum_3.values": "blob_e3184e13cd1bc1f1",
          "position": "blob_b506867099007436",
          "sm.sum_6.values": "blob_e3184e13cd1bc1f1",
          "flt.rng_1.values": "blob_e3184e13cd1bc1f1",
          "sm.sum_4.values": "blob_e3184e13cd1bc1f1"
        }
      }
    },
    "b": {
      "id": "b",
      "type": "circle",
      "group": null,
      "data_columns": {
        "position": {
          "values": {
            "ref": "position"
          },
          "size": 2
        }
      },
      "base_encodings": {
        "radius": {
          "value": 6
        },
        "lineWidth": {
          "value": 1
        },
        "fillColor": {
          "value": [
            30,
            144,
            255,
            204
          ]
        },
        "lineColor": {
          "value": [
            0,
            0,
            139,
            255
          ]
        }
      },
      "cfg": {
        "pickable": true,
        "stroke": true,
        "radiusUnits": "pixels",
        "lineWidthUnits": "pixels"
      },
      "bbox": [
        0.04,
        51.5,
        0.05,
        51.5
      ],
      "coordinate_origin": [
        0.04499999999998749,
        51.5
      ],
      "dataStore": {
        "blobs": {
          "blob_c6f44e98ed48fbee": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,CtejuwAAAAAK16M7AAAAAA=="
            },
            "length": 4
          },
          "blob_829502619745fdfb": {
            "dtype": "f32",
            "href": {
              "data": "data:application/octet-stream;base64,AAAAQAAAwH8="
            },
            "length": 2
          }
        },
        "refs": {
          "sm.sum_11.values": "blob_829502619745fdfb",
          "sm.sum_10.values": "blob_829502619745fdfb",
          "position": "blob_c6f44e98ed48fbee",
          "sm.sum_9.values": "blob_829502619745fdfb",
          "sm.sum_12.values": "blob_829502619745fdfb"
        }
      }
    }
  },
  ".__components": {
    "views": [

    ],
    "range": {
      "rng_1": {
        "type": "range",
        "id": "rng_1",
        "layer": "a",
        "bind": "filters",
        "position": null,
        "label": "v",
        "default": null,
        "min": -1,
        "max": 1,
        "step": null,
        "live": true,
        "values": {
          "ref": "flt.rng_1.values"
        },
        "values_ref_hint": "flt.rng_1.values"
      }
    },
    "select": [

    ],
    "legends": [

    ],
    "summaries": {
      "sum_1": {
        "type": "summaries",
        "id": "sum_1",
        "layer": "a",
        "bind": "summaries",
        "position": null,
        "label": "n",
        "op": "count"
      },
      "sum_2": {
        "type": "summaries",
        "id": "sum_2",
        "layer": "a",
        "bind": "summaries",
        "position": null,
        "label": "known",
        "op": "count"
      },
      "sum_3": {
        "type": "summaries",
        "id": "sum_3",
        "layer": "a",
        "bind": "summaries",
        "position": null,
        "label": "sum",
        "op": "sum",
        "na_rm": true,
        "values": {
          "ref": "sm.sum_3.values"
        },
        "values_ref_hint": "sm.sum_3.values"
      },
      "sum_4": {
        "type": "summaries",
        "id": "sum_4",
        "layer": "a",
        "bind": "summaries",
        "position": null,
        "label": "mean",
        "op": "mean",
        "digits": 2,
        "na_rm": true,
        "values": {
          "ref": "sm.sum_4.values"
        },
        "values_ref_hint": "sm.sum_4.values"
      },
      "sum_5": {
        "type": "summaries",
        "id": "sum_5",
        "layer": "a",
        "bind": "summaries",
        "position": null,
        "label": "min",
        "op": "min",
        "na_rm": true,
        "values": {
          "ref": "sm.sum_5.values"
        },
        "values_ref_hint": "sm.sum_5.values"
      },
      "sum_6": {
        "type": "summaries",
        "id": "sum_6",
        "layer": "a",
        "bind": "summaries",
        "position": null,
        "label": "max",
        "op": "max",
        "na_rm": true,
        "values": {
          "ref": "sm.sum_6.values"
        },
        "values_ref_hint": "sm.sum_6.values"
      },
      "sum_7": {
        "type": "summaries",
        "id": "sum_7",
        "layer": "b",
        "bind": "summaries",
        "position": null,
        "label": "n",
        "op": "count"
      },
      "sum_8": {
        "type": "summaries",
        "id": "sum_8",
        "layer": "b",
        "bind": "summaries",
        "position": null,
        "label": "known",
        "op": "count"
      },
      "sum_9": {
        "type": "summaries",
        "id": "sum_9",
        "layer": "b",
        "bind": "summaries",
        "position": null,
        "label": "sum",
        "op": "sum",
        "na_rm": true,
        "values": {
          "ref": "sm.sum_9.values"
        },
        "values_ref_hint": "sm.sum_9.values"
      },
      "sum_10": {
        "type": "summaries",
        "id": "sum_10",
        "layer": "b",
        "bind": "summaries",
        "position": null,
        "label": "mean",
        "op": "mean",
        "digits": 2,
        "na_rm": true,
        "values": {
          "ref": "sm.sum_10.values"
        },
        "values_ref_hint": "sm.sum_10.values"
      },
      "sum_11": {
        "type": "summaries",
        "id": "sum_11",
        "layer": "b",
        "bind": "summaries",
        "position": null,
        "label": "min",
        "op": "min",
        "na_rm": true,
        "values": {
          "ref": "sm.sum_11.values"
        },
        "values_ref_hint": "sm.sum_11.values"
      },
      "sum_12": {
        "type": "summaries",
        "id": "sum_12",
        "layer": "b",
        "bind": "summaries",
        "position": null,
        "label": "max",
        "op": "max",
        "na_rm": true,
        "values": {
          "ref": "sm.sum_12.values"
        },
        "values_ref_hint": "sm.sum_12.values"
      }
    }
  },
  ".__controls": {
    "filters": {
      "type": "filters",
      "controls": {
        "v": {
          "type": "range",
          "label": "v",
          "members": [
            "rng_1"
          ],
          "domain": {
            "min": -1,
            "max": 1
          },
          "live": true
        }
      },
      "order": [
        "v"
      ]
    },
    "summaries": {
      "type": "summaries",
      "rows": {
        "n": {
          "op": "count",
          "label": "n",
          "members": [
            "sum_1",
            "sum_7"
          ]
        },
        "known": {
          "op": "count",
          "label": "known",
          "members": [
            "sum_2",
            "sum_8"
          ]
        },
        "sum": {
          "op": "sum",
          "label": "sum",
          "members": [
            "sum_3",
            "sum_9"
          ],
          "na_rm": true
        },
        "mean": {
          "op": "mean",
          "label": "mean",
          "members": [
            "sum_4",
            "sum_10"
          ],
          "digits": 2,
          "na_rm": true
        },
        "min": {
          "op": "min",
          "label": "min",
          "members": [
            "sum_5",
            "sum_11"
          ],
          "na_rm": true
        },
        "max": {
          "op": "max",
          "label": "max",
          "members": [
            "sum_6",
            "sum_12"
          ],
          "na_rm": true
        }
      },
      "order": [
        "n",
        "known",
        "sum",
        "mean",
        "min",
        "max"
      ]
    }
  },
  ".__panel": null
} as const satisfies WireSpec;
