# Writes the specs the unit tests check the TypeScript spec definition against.
# Run from the package root:
#   Rscript tests/unit/make-spec-samples.R
# Each sample is the JSON htmlwidgets would send to the browser, wrapped as a TypeScript
# module. Regenerate after any change to what the R compiler emits.

if (requireNamespace("pkgload", quietly = TRUE)) {
  pkgload::load_all(".", quiet = TRUE)
} else {
  library(maplamina)
}
library(sf)

out_dir <- file.path("tests", "unit", "spec-samples")
unlink(out_dir, recursive = TRUE)
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

# typed = FALSE leaves out the check against WireSpec, for a spec the definition does not admit.
save <- function(widget, name, typed = TRUE) {
  x <- .ml_prerender(widget)$x
  json <- jsonlite::prettify(htmlwidgets:::toJSON(x), indent = 2)
  path <- file.path(out_dir, paste0(name, ".ts"))
  con <- file(path, open = "wb")
  on.exit(close(con))
  writeLines(c(
    "// Generated by tests/unit/make-spec-samples.R. Do not edit.",
    if (typed) "import type { WireSpec } from '../../../srcjs/core/spec-types';" else "// Not checked against WireSpec.",
    "",
    paste0("export default ", sub("\\s+$", "", json), if (typed) " as const satisfies WireSpec;" else " as const;")
  ), con, sep = "\n", useBytes = TRUE)
  cat("wrote", path, "\n")
}

pts <- data.frame(
  lon = c(-0.02, 0, 0.02),
  lat = c(51.49, 51.5, 51.51),
  v = c(1.5, 2, 3.5),
  n = c(1L, 2L, 3L),
  g = c("a", "b", "a"),
  day = as.Date(c("2026-01-01", "2026-01-02", "2026-01-03"))
)

square <- function(x, y, r = 0.01) {
  st_polygon(list(rbind(c(x - r, y - r), c(x + r, y - r), c(x + r, y + r), c(x - r, y + r), c(x - r, y - r))))
}
polys <- st_sf(
  v = c(10, 1),
  g = c("a", "b"),
  geometry = st_sfc(st_multipolygon(list(square(-0.03, 51.5), square(0, 51.5))), square(0.03, 51.5), crs = 4326)
)
lines <- st_sf(
  v = c(1, 2),
  g = c("a", "b"),
  geometry = st_sfc(
    st_linestring(rbind(c(-0.03, 51.49), c(0.03, 51.49))),
    st_linestring(rbind(c(-0.03, 51.51), c(0.03, 51.51))),
    crs = 4326
  )
)

maplamina() |>
  save("empty")

maplamina(pts) |>
  add_circles(
    fill_color = "darkblue",
    tooltip = tmpl("{g} {v:.1f} {n} {day}"),
    popup = tmpl("<b>{g}</b>", html = TRUE)
  ) |>
  save("circles-constant")

maplamina(pts, projection = "globe", fit_bounds = FALSE, dragRotate = TRUE) |>
  add_circles(
    radius = ~v, width = ~v, fill_color = ~g, color = color_numeric(~v, "viridis"),
    radius_units = "meters", radius_min_pixels = 2, radius_max_pixels = 40,
    width_min_pixels = 1, width_max_pixels = 4, group = "points", id = "pts"
  ) |>
  add_scalebar() |>
  add_fullscreen() |>
  add_geolocate() |>
  save("circles-per-feature")

maplamina(lines) |>
  add_lines(width = 4, width_min_pixels = 1, width_max_pixels = 20, tooltip = tmpl("plain")) |>
  add_views(
    view("thin", width = 2),
    view("by value", width = ~v, color = ~g),
    view("flat", color = "red"),
    duration = 500, easing = "linear", position = "topright"
  ) |>
  save("lines-views")

maplamina(polys) |>
  add_polygons(fill_color = color_factor(~g, c("red", "blue")), width = 2) |>
  add_views(
    view("scale", fill_color = color_numeric(~v, "viridis")), view("flat", fill_color = "red"),
    bind = "views"
  ) |>
  add_filters(
    filter_select(~g, default = c("a", "b"), dropdown = TRUE, max_levels = 5),
    filter_range(~v, default = c(1, 5), step = 0.5, live = FALSE),
    bind = "filters"
  ) |>
  add_summaries(
    summary_count(label = "n"),
    summary_sum(~v, label = "sum", digits = 1, prefix = "$", suffix = " m"),
    summary_mean(~v, label = "mean"),
    summary_min(~v, label = "min"),
    summary_max(~v, label = "max"),
    bind = "summaries"
  ) |>
  add_panel(
    title = "Panel", description = "About", position = "bottomright",
    sections = sections(section("views"), section("filters"), section("summaries"))
  ) |>
  save("polygons-components")

maplamina(pts) |>
  add_icons(icon = "star", size = 24, size_units = "meters", size_min_pixels = 4, color = ~g) |>
  add_views(view("big", size = 40), view("by value", size = ~v)) |>
  add_markers(size = ~v, color = "red", size_max_pixels = 48) |>
  save("icons-markers")

maplamina(pts) |>
  add_circles() |>
  add_views(view("a", radius = 4), view("b", radius = 8)) |>
  add_legend(
    title = "Groups", type = "categorical", values = c("a", "b"), colors = c("red", "blue"),
    shapes = c("circle", "geo_alt_fill"), sizes = c(10, 14)
  ) |>
  add_legend(
    type = "continuous", range = c(0, 1), gradient = c("white", "red"), labels = c("low", "high"),
    breaks = c(0, 1), shape = "line", size = 4, layer = "circle1", view = c("a", "b"), bind = "scale",
    position = "topleft"
  ) |>
  save("legends")

# Length-1 vectors arrive as scalars.
maplamina(pts[1, ]) |>
  add_circles(tooltip = tmpl("{g}")) |>
  add_filters(filter_select(~g, default = "a")) |>
  add_legend(type = "categorical", values = "only", colors = "red") |>
  add_legend(
    type = "continuous", range = c(0, 1), gradient = c("white", "red"), labels = "low", breaks = 0.5,
    view = "a"
  ) |>
  save("length-one")

# A numeric column under a select, with a numeric default. The default is emitted as a
# number, which WireSpec does not admit for a select.
maplamina(pts) |>
  add_circles() |>
  add_filters(filter_select(~n, default = 2)) |>
  save("select-numeric-default", typed = FALSE)

# Two layers under one select and one range: disjoint categories, NA in both columns.
pts_b <- data.frame(
  lon = c(0.04, 0.05, 0.06),
  lat = c(51.5, 51.5, 51.5),
  v = c(0, NA, 4),
  g = c("c", NA, "c")
)
maplamina() |>
  add_circles(pts, id = "a") |>
  add_filters(filter_select(~g), filter_range(~v), bind = "filters") |>
  add_circles(pts_b, id = "b") |>
  add_filters(filter_select(~g), filter_range(~v), bind = "filters") |>
  save("filters-two-layers")

# Two layers under one set of summaries, NA in both columns; a range on the first only.
pts_na <- data.frame(lon = c(-0.02, 0, 0.02), lat = c(51.5, 51.5, 51.5), v = c(-1, NA, 1))
pts_nb <- data.frame(lon = c(0.04, 0.05), lat = c(51.5, 51.5), v = c(2, NA))
maplamina() |>
  add_circles(pts_na, id = "a") |>
  add_filters(filter_range(~v), bind = "filters") |>
  add_summaries(
    summary_count(label = "n"), summary_count(~v, label = "known"), summary_sum(~v, label = "sum"),
    summary_mean(~v, label = "mean", digits = 2), summary_min(~v, label = "min"),
    summary_max(~v, label = "max"),
    bind = "summaries"
  ) |>
  add_circles(pts_nb, id = "b") |>
  add_summaries(
    summary_count(label = "n"), summary_count(~v, label = "known"), summary_sum(~v, label = "sum"),
    summary_mean(~v, label = "mean", digits = 2), summary_min(~v, label = "min"),
    summary_max(~v, label = "max"),
    bind = "summaries"
  ) |>
  save("summaries-na")

# A count beside a range over values that are not exact in float32.
pts_f <- data.frame(lon = c(-0.04, -0.02, 0, 0.02, 0.04), lat = 51.5, v = c(0.3, 0.5, 0.7, 0.9, 1.1))
maplamina(pts_f) |>
  add_circles() |>
  add_filters(filter_range(~v), bind = "filters") |>
  add_summaries(summary_count(label = "n"), bind = "summaries") |>
  save("range-float32")
